#include "images.h"

const ext_img_desc_t images[34] = {
    { "ordinary", &img_ordinary },
    { "full-not-charging", &img_full_not_charging },
    { "good", &img_good },
    { "dead", &img_dead },
    { "nothing", &img_nothing },
    { "temp-normal", &img_temp_normal },
    { "happy", &img_happy },
    { "base", &img_base },
    { "battery-3-not-charging", &img_battery_3_not_charging },
    { "battery-2-not-charging", &img_battery_2_not_charging },
    { "battery-1-not-charging", &img_battery_1_not_charging },
    { "battery-1-charging", &img_battery_1_charging },
    { "battery-2-charging", &img_battery_2_charging },
    { "battery-3-charging", &img_battery_3_charging },
    { "battery-full-charging", &img_battery_full_charging },
    { "crit", &img_crit },
    { "bad", &img_bad },
    { "damp", &img_damp },
    { "mid", &img_mid },
    { "dry", &img_dry },
    { "minus", &img_minus },
    { "plus", &img_plus },
    { "diver", &img_diver },
    { "dizzy", &img_dizzy },
    { "sad", &img_sad },
    { "temp-minus", &img_temp_minus },
    { "temp-plus", &img_temp_plus },
    { "ordinary-nimbus", &img_ordinary_nimbus },
    { "cat-huh", &img_cat_huh },
    { "ultra-happy", &img_ultra_happy },
    { "choice-no", &img_choice_no },
    { "choice-yes", &img_choice_yes },
    { "lightning-charge", &img_lightning_charge },
    { "warn", &img_warn },
};
